server:
  port: 8001
spring:
  application:
    name: BLACKCAT-PLAT
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///blackcat-plat?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root