server:
  port: 9997
spring:
  application:
    name: BLACKCAT-ZUUL-GATEWAY
zuul:
  ignored-services: "*" #用*来通配符，忽略从9998端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀
  routes:  #路由
    plat:
      path: /plat/**
      service-id: blackcat-plat