server:
  port: 9998
spring:
  application:
    name: BLACKCAT-ZUUL-GATEWAY
zuul:
  ignored-services: "*" #用*来通配符，忽略从9527端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀
  routes:
    plat:
      path: /plat/**
      service-id: blackcat-plat
    product:
      path: /product/**
      service-id: blackcat-product
	common:
      path: /common/**
      service-id: blackcat-common
blackcat-product:
  ribbon:
   ConnectTimeout: 1000
   ReadTimeout: 5000
blackcat-common:
  ribbon:
   ConnectTimeout: 1000
   ReadTimeout: 5000